#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Feature & Stage Attention Models
================================

Four lightweight variants that run on the existing 5 s preference dataset:

1. FeatureWeightedModel – learns per-feature importance after aggregating
   across time (mean/std of left-right differences).
2. FeatureStageAttentionModel – learns both stage-level (1 s segments) and
   feature-level attention jointly, providing time × feature interpretability.
3. FeatureStageGRUModel – uses GRU for temporal accumulation instead of attention.
4. Comparison models – various ear comparison strategies with temporal modeling.

All models reuse the cached multi-feature datasets generated by
attention_loudness_model.py (500 ms resolution). This script simply builds
stage-wise statistics on top and trains the new attention heads.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Tuple, List, Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, Subset
import matplotlib.pyplot as plt

from attention_loudness_model import (  # type: ignore
    load_or_build_cached_dataset,
    get_feature_configs_from_linear_regression,
    get_trials,
)
from linear_regression_selected_features import (
    load_or_extract_features,
    merge_balanced_pairs_by_type,
    calculate_selection_probability_144,
)

SR = 16000
HOP = 8000  # 500 ms per frame
DEFAULT_STAGE_SECONDS = 1.0  # 1 s stage for time attention
RNG_SEED = 42
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# --------------------------------------------------------------------------- #
# Dataset helpers
# --------------------------------------------------------------------------- #
def _compute_stage_features(
    sample: np.ndarray,
    n_stages: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Convert a (2*F, T) sample into:
      - stage_features: (n_stages, feat_dim) where feat_dim = 2*F (mean+std diff)
      - global_features: (feat_dim,) overall mean/std diff
    """
    channels, time_steps = sample.shape
    assert channels % 2 == 0, "Sample must contain left/right feature stacks."
    n_features = channels // 2

    left = sample[:n_features]
    right = sample[n_features:]
    diff = left - right  # (F, T)

    left_mean = left.mean(axis=1)
    left_std = left.std(axis=1)
    right_mean = right.mean(axis=1)
    right_std = right.std(axis=1)

    global_diff = np.concatenate([left_mean - right_mean, left_std - right_std], axis=0)
    left_global = np.concatenate([left_mean, left_std], axis=0)
    right_global = np.concatenate([right_mean, right_std], axis=0)

    # Stage stats
    frames_per_stage = max(1, time_steps // n_stages)
    stage_diff_vectors: List[np.ndarray] = []
    stage_left_vectors: List[np.ndarray] = []
    stage_right_vectors: List[np.ndarray] = []
    for s in range(n_stages):
        start = s * frames_per_stage
        end = time_steps if s == n_stages - 1 else min(time_steps, (s + 1) * frames_per_stage)
        slice_diff = diff[:, start:end]
        slice_left = left[:, start:end]
        slice_right = right[:, start:end]
        if slice_diff.size == 0:
            diff_mean = np.zeros(n_features, dtype=np.float32)
            diff_std = np.zeros(n_features, dtype=np.float32)
            left_mean = np.zeros(n_features, dtype=np.float32)
            left_std = np.zeros(n_features, dtype=np.float32)
            right_mean = np.zeros(n_features, dtype=np.float32)
            right_std = np.zeros(n_features, dtype=np.float32)
        else:
            diff_mean = slice_diff.mean(axis=1)
            diff_std = slice_diff.std(axis=1)
            left_mean = slice_left.mean(axis=1)
            left_std = slice_left.std(axis=1)
            right_mean = slice_right.mean(axis=1)
            right_std = slice_right.std(axis=1)
        stage_diff_vectors.append(np.concatenate([diff_mean, diff_std], axis=0))
        stage_left_vectors.append(np.concatenate([left_mean, left_std], axis=0))
        stage_right_vectors.append(np.concatenate([right_mean, right_std], axis=0))

    stage_features = np.stack(stage_diff_vectors, axis=0)  # (n_stages, feat_dim)
    stage_left = np.stack(stage_left_vectors, axis=0)
    stage_right = np.stack(stage_right_vectors, axis=0)
    return (
        stage_features.astype(np.float32),
        global_diff.astype(np.float32),
        left_global.astype(np.float32),
        right_global.astype(np.float32),
        stage_left.astype(np.float32),
        stage_right.astype(np.float32),
    )


class StageFeatureDataset(Dataset):
    """
    Materializes global/stage features for all samples to enable
    fast subset access during K-fold cross-validation.
    """

    def __init__(
        self,
        base_dataset: Dataset,
        stage_seconds: float = DEFAULT_STAGE_SECONDS,
        feature_configs: Optional[List[Tuple[str, bool]]] = None,
    ):
        self.base = base_dataset
        sample, _ = self.base[0]
        _, time_steps = sample.shape
        frames_per_stage = max(1, int(round((stage_seconds * SR) / HOP)))
        self.n_stages = max(1, time_steps // frames_per_stage)
        self.feat_dim = (sample.shape[0] // 2) * 2  # mean+std per feature

        if feature_configs:
            base_names = [cfg[0] for cfg in feature_configs]
        else:
            base_names = [f"feat_{i+1}" for i in range(self.feat_dim // 2)]
        self.stage_labels = [f"Stage {i + 1}" for i in range(self.n_stages)]
        ear_labels: List[str] = []
        for name in base_names:
            ear_labels.append(f"{name}_mean")
            ear_labels.append(f"{name}_std")
        self.ear_feature_labels = ear_labels

        global_list: List[np.ndarray] = []
        left_list: List[np.ndarray] = []
        right_list: List[np.ndarray] = []
        stage_list: List[np.ndarray] = []
        left_stage_list: List[np.ndarray] = []
        right_stage_list: List[np.ndarray] = []
        target_list: List[float] = []

        for idx in range(len(self.base)):
            feat, tgt = self.base[idx]
            (
                stage_feat,
                global_feat,
                left_global,
                right_global,
                stage_left,
                stage_right,
            ) = _compute_stage_features(feat, self.n_stages)
            stage_list.append(stage_feat)
            global_list.append(global_feat)
            left_list.append(left_global)
            right_list.append(right_global)
            left_stage_list.append(stage_left)
            right_stage_list.append(stage_right)
            target_list.append(float(tgt))

        self.global_feats = np.stack(global_list, axis=0)
        self.stage_feats = np.stack(stage_list, axis=0)
        self.left_globals = np.stack(left_list, axis=0)
        self.right_globals = np.stack(right_list, axis=0)
        self.stage_left_feats = np.stack(left_stage_list, axis=0)
        self.stage_right_feats = np.stack(right_stage_list, axis=0)
        self.targets = np.asarray(target_list, dtype=np.float32)
        self.left_feat_dim = self.left_globals.shape[1]
        self.ear_stage_feat_dim = self.stage_left_feats.shape[2]

    def __len__(self) -> int:
        return self.global_feats.shape[0]

    def __getitem__(self, idx: int):
        global_feat = torch.from_numpy(self.global_feats[idx])
        stage_feat = torch.from_numpy(self.stage_feats[idx])
        target = torch.tensor(self.targets[idx], dtype=torch.float32)
        return global_feat, stage_feat, target


class FeatureOnlyDataset(Dataset):
    """Thin wrapper exposing only (global_feat, target)."""

    def __init__(self, stage_dataset: StageFeatureDataset, indices: np.ndarray):
        self.stage_dataset = stage_dataset
        self.indices = indices

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, idx: int):
        real_idx = self.indices[idx]
        global_feat = torch.from_numpy(self.stage_dataset.global_feats[real_idx])
        target = torch.tensor(self.stage_dataset.targets[real_idx], dtype=torch.float32)
        return global_feat, target


class StageDiffDataset(Dataset):
    """Returns stage-wise diff features."""

    def __init__(self, stage_dataset: StageFeatureDataset, indices: np.ndarray):
        self.stage_dataset = stage_dataset
        self.indices = indices

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, idx: int):
        real_idx = self.indices[idx]
        stage_feat = torch.from_numpy(self.stage_dataset.stage_feats[real_idx])
        target = torch.tensor(self.stage_dataset.targets[real_idx], dtype=torch.float32)
        return stage_feat, target


class LeftRightDataset(Dataset):
    """Returns (left_feat, right_feat, target) for global comparison models."""

    def __init__(self, stage_dataset: StageFeatureDataset, indices: np.ndarray):
        self.stage_dataset = stage_dataset
        self.indices = indices

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, idx: int):
        real_idx = self.indices[idx]
        left_feat = torch.from_numpy(self.stage_dataset.left_globals[real_idx])
        right_feat = torch.from_numpy(self.stage_dataset.right_globals[real_idx])
        target = torch.tensor(self.stage_dataset.targets[real_idx], dtype=torch.float32)
        return left_feat, right_feat, target


class StageSequenceDataset(Dataset):
    """Returns stage-wise left/right sequences for attention models."""

    def __init__(self, stage_dataset: StageFeatureDataset, indices: np.ndarray):
        self.stage_dataset = stage_dataset
        self.indices = indices

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, idx: int):
        real_idx = self.indices[idx]
        left_seq = torch.from_numpy(self.stage_dataset.stage_left_feats[real_idx])
        right_seq = torch.from_numpy(self.stage_dataset.stage_right_feats[real_idx])
        target = torch.tensor(self.stage_dataset.targets[real_idx], dtype=torch.float32)
        return left_seq, right_seq, target


# --------------------------------------------------------------------------- #
# Models
# --------------------------------------------------------------------------- #
class FeatureWeightedModel(nn.Module):
    """
    Learns per-feature importance on top of global statistics.
    """

    def __init__(self, feature_dim: int, hidden_dim: int = 64, dropout: float = 0.2):
        super().__init__()
        self.feature_gate = nn.Sequential(
            nn.Linear(feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, feature_dim),
            nn.Sigmoid(),
        )
        self.regressor = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        weights = self.feature_gate(x)
        gated = x * weights
        pred = torch.sigmoid(self.regressor(gated)).squeeze(-1)
        return pred, weights


class FeatureStageAttentionModel(nn.Module):
    """
    Joint stage (time) + feature attention.
    Input shape: (batch, n_stages, feature_dim)
    """

    def __init__(self, n_stages: int, feature_dim: int, hidden_dim: int = 64, dropout: float = 0.2):
        super().__init__()
        self.n_stages = n_stages
        self.feature_dim = feature_dim

        self.stage_attn = nn.Sequential(
            nn.Linear(feature_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, 1),
        )
        self.feature_gate = nn.Sequential(
            nn.Linear(feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, feature_dim),
            nn.Sigmoid(),
        )
        self.regressor = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        # x: (batch, n_stages, feature_dim)
        stage_scores = self.stage_attn(x).squeeze(-1)  # (batch, n_stages)
        stage_weights = torch.softmax(stage_scores, dim=1)
        context = torch.sum(stage_weights.unsqueeze(-1) * x, dim=1)  # (batch, feature_dim)

        feature_weights = self.feature_gate(context)
        gated = context * feature_weights
        pred = torch.sigmoid(self.regressor(gated)).squeeze(-1)
        return pred, stage_weights, feature_weights


class SimpleTemporalModel(nn.Module):
    """
    极简时间建模：学习时间权重进行加权平均
    最简单的时序处理，避免过拟合
    Input shape: (batch, n_stages, feature_dim)
    """

    def __init__(self, n_stages: int, feature_dim: int, hidden_dim: int = 16):
        super().__init__()
        self.n_stages = n_stages
        self.feature_dim = feature_dim

        # 学习到的时间权重（最简单的时序建模）
        self.time_weights = nn.Parameter(torch.ones(n_stages) / n_stages)

        # 简单的特征聚合
        self.feature_agg = nn.Sequential(
            nn.Linear(feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )

        # 预测头
        self.regressor = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Linear(hidden_dim // 2, 1),
        )

        # 简单初始化
        for param in self.parameters():
            if param.dim() > 1:
                nn.init.xavier_uniform_(param, gain=0.1)
            else:
                nn.init.constant_(param, 0)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        极简时间建模：学习时间权重进行加权平均

        Args:
            x: (batch, n_stages, feature_dim) - 分阶段特征

        Returns:
            pred: 预测值
            time_weights: 学习到的时间权重
        """
        batch_size = x.size(0)

        # 确保时间权重是概率分布
        time_weights = torch.softmax(self.time_weights, dim=0)

        # 对每个时间步的特征进行聚合
        stage_features = []
        for t in range(self.n_stages):
            stage_feat = self.feature_agg(x[:, t, :])  # (batch, hidden_dim)
            stage_features.append(stage_feat)

        # 堆叠所有时间步
        stage_features = torch.stack(stage_features, dim=1)  # (batch, n_stages, hidden_dim)

        # 时间加权平均
        weighted_features = torch.sum(stage_features * time_weights.unsqueeze(0).unsqueeze(-1), dim=1)  # (batch, hidden_dim)

        # 预测
        pred = self.regressor(weighted_features).squeeze(-1)  # (batch,)

        return pred, time_weights

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        使用GRU进行时间累加，而不是注意力聚合

        Args:
            x: (batch, n_stages, feature_dim) - 分阶段特征

        Returns:
            pred: 预测概率
            accumulation_weights: 特征权重
        """
        batch_size = x.size(0)

        # 确保memory_decay在合理范围内
        clamped_decay = torch.clamp(self.memory_decay, self.min_decay, self.max_decay)

        # 初始化积累状态
        accumulation_state = torch.zeros(batch_size, self.feature_dim, device=x.device)

        # GRU累加过程
        for t in range(self.n_stages):
            current_input = x[:, t, :]  # (batch, feature_dim)

            # GRU更新
            new_state = self.gru_cell(current_input, accumulation_state)

            # 应用记忆衰减（生物机制）
            accumulation_state = new_state * clamped_decay + current_input * (1 - clamped_decay)

        # 最终积累状态作为上下文
        context = accumulation_state  # (batch, feature_dim)

        # 特征门控
        feature_weights = self.feature_gate(context)
        gated = context * feature_weights

        # 预测（回归任务，直接输出连续值）
        pred = self.regressor(gated).squeeze(-1)

        # 调试：确保输出是合理的概率值
        print(f"DEBUG: pred range: {pred.min().item():.4f} - {pred.max().item():.4f}")
        print(f"DEBUG: pred mean: {pred.mean().item():.4f}")
        print(f"DEBUG: pred std: {pred.std().item():.4f}")

        return pred, feature_weights


class SharedEarComparisonModel(nn.Module):
    """
    Scores left/right ears with shared weights, then compares.
    """

    def __init__(self, ear_feature_dim: int, hidden_dim: int = 64, dropout: float = 0.2):
        super().__init__()
        self.feature_gate = nn.Sequential(
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, ear_feature_dim),
            nn.Sigmoid(),
        )
        self.scorer = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def _score(self, ear_feat: torch.Tensor):
        gated = ear_feat * self.feature_gate(ear_feat)
        return self.scorer(gated).squeeze(-1)

    def forward(self, left_feat: torch.Tensor, right_feat: torch.Tensor):
        left_score = self._score(left_feat)
        right_score = self._score(right_feat)
        pred = torch.sigmoid(left_score - right_score)
        return pred, left_score, right_score


class IndependentEarComparisonModel(nn.Module):
    """
    Scores left/right ears with independent weights before comparison.
    """

    def __init__(self, ear_feature_dim: int, hidden_dim: int = 64, dropout: float = 0.2):
        super().__init__()
        self.left_gate = nn.Sequential(
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, ear_feature_dim),
            nn.Sigmoid(),
        )
        self.right_gate = nn.Sequential(
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, ear_feature_dim),
            nn.Sigmoid(),
        )
        self.left_scorer = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )
        self.right_scorer = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, left_feat: torch.Tensor, right_feat: torch.Tensor):
        left_score = self.left_scorer(left_feat * self.left_gate(left_feat)).squeeze(-1)
        right_score = self.right_scorer(right_feat * self.right_gate(right_feat)).squeeze(-1)
        pred = torch.sigmoid(left_score - right_score)
        return pred, left_score, right_score


class AdditiveTimeAttention(nn.Module):
    """Additive attention over the time dimension."""

    def __init__(self, input_dim: int, hidden_dim: int):
        super().__init__()
        self.proj = nn.Linear(input_dim, hidden_dim)
        self.v = nn.Linear(hidden_dim, 1, bias=False)

    def forward(self, seq: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        # seq: (batch, T, input_dim)
        u = torch.tanh(self.proj(seq))  # (batch, T, hidden_dim)
        scores = self.v(u).squeeze(-1)  # (batch, T)
        weights = torch.softmax(scores, dim=1)
        context = torch.bmm(weights.unsqueeze(1), seq).squeeze(1)
        return context, weights


class PerFeatureTimeAttention(nn.Module):
    """Time attention applied per feature dimension independently."""

    def __init__(self, n_features: int, attn_hidden: int = 32):
        super().__init__()
        # Create separate attention for each feature dimension
        self.feature_attentions = nn.ModuleList([
            AdditiveTimeAttention(1, attn_hidden) for _ in range(n_features)
        ])

    def forward(self, seq: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        # seq: (batch, T, n_features)
        batch_size, T, n_features = seq.shape

        # Apply attention to each feature independently
        attended_features = []
        attention_weights = []

        for i in range(n_features):
            # Extract i-th feature across time: (batch, T, 1)
            feature_seq = seq[:, :, i:i+1]
            # Apply attention: returns (batch, 1), (batch, T)
            context, weights = self.feature_attentions[i](feature_seq)
            attended_features.append(context.squeeze(-1))  # (batch,)
            attention_weights.append(weights)  # (batch, T)

        # Stack attended features: (batch, n_features)
        context_vector = torch.stack(attended_features, dim=1)
        # Stack weights: (batch, n_features, T)
        weights_tensor = torch.stack(attention_weights, dim=1)

        return context_vector, weights_tensor


class StageAwareSharedComparisonUnified(nn.Module):
    """
    Stage attention shared across ears with per-feature time weights, feature gates shared.
    """

    def __init__(self, ear_feature_dim: int, attn_hidden: int = 64, hidden_dim: int = 64, dropout: float = 0.2):
        super().__init__()
        self.shared_attn = PerFeatureTimeAttention(ear_feature_dim, attn_hidden)
        self.feature_gate = nn.Sequential(
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, ear_feature_dim),
            nn.Sigmoid(),
        )
        self.scorer = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, left_seq: torch.Tensor, right_seq: torch.Tensor):
        left_context, left_weights = self.shared_attn(left_seq)
        right_context, right_weights = self.shared_attn(right_seq)
        gate = self.feature_gate(left_context)  # shared gate applied to both contexts
        left_score = self.scorer(left_context * gate).squeeze(-1)
        right_score = self.scorer(right_context * gate).squeeze(-1)
        pred = torch.sigmoid(left_score - right_score)
        return pred, left_weights, right_weights, gate, gate  # return gate twice for compatibility



class StageAwareSharedComparisonModel(nn.Module):
    """
    Shared ear weights with per-ear time attention over stage features.
    """

    def __init__(self, ear_feature_dim: int, attn_hidden: int = 64, hidden_dim: int = 64, dropout: float = 0.2):
        super().__init__()
        self.left_attn = AdditiveTimeAttention(ear_feature_dim, attn_hidden)
        self.right_attn = AdditiveTimeAttention(ear_feature_dim, attn_hidden)
        self.feature_gate = nn.Sequential(
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, ear_feature_dim),
            nn.Sigmoid(),
        )
        self.scorer = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(ear_feature_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, left_seq: torch.Tensor, right_seq: torch.Tensor):
        left_context, left_weights = self.left_attn(left_seq)
        right_context, right_weights = self.right_attn(right_seq)
        left_gate = self.feature_gate(left_context)
        right_gate = self.feature_gate(right_context)
        left_score = self.scorer(left_context * left_gate).squeeze(-1)
        right_score = self.scorer(right_context * right_gate).squeeze(-1)
        pred = torch.sigmoid(left_score - right_score)
        return pred, left_weights, right_weights, left_gate, right_gate


# --------------------------------------------------------------------------- #
# Training utilities
# --------------------------------------------------------------------------- #
@dataclass
class TrainConfig:
    lr: float = 1e-3
    weight_decay: float = 1e-4
    epochs: int = 80
    patience: int = 15
    batch_size: int = 64


def train_model(
    model: nn.Module,
    train_loader: DataLoader,
    val_loader: Optional[DataLoader],
    cfg: TrainConfig,
) -> Tuple[nn.Module, List[float], List[float]]:
    criterion = nn.MSELoss()  # Mean Squared Error for regression
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)

    best_state = None
    best_val = float("inf")
    patience = 0
    train_curve: List[float] = []
    val_curve: List[float] = []

    for epoch in range(1, cfg.epochs + 1):
        model.train()
        epoch_loss = 0.0
        for batch in train_loader:
            inputs, targets = batch
            inputs = inputs.to(DEVICE)
            targets = targets.to(DEVICE)
            preds = model(inputs)[0] if isinstance(model, FeatureWeightedModel) else model(inputs)[0]
            loss = criterion(preds, targets)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item() * targets.size(0)
        avg_train = epoch_loss / len(train_loader.dataset)
        train_curve.append(avg_train)

        if val_loader is not None:
            model.eval()
            val_loss = 0.0
            with torch.no_grad():
                for batch in val_loader:
                    inputs, targets = batch
                    inputs = inputs.to(DEVICE)
                    targets = targets.to(DEVICE)
                    preds = model(inputs)[0] if isinstance(model, FeatureWeightedModel) else model(inputs)[0]
                    val_loss += criterion(preds, targets).item() * targets.size(0)
            avg_val = val_loss / len(val_loader.dataset)
            val_curve.append(avg_val)
            if avg_val < best_val - 1e-5:
                best_val = avg_val
                best_state = model.state_dict()
                patience = 0
            else:
                patience += 1
            if patience >= cfg.patience:
                break
        else:
            best_state = model.state_dict()

    if best_state is not None:
        model.load_state_dict(best_state)
    return model, train_curve, val_curve


def evaluate_model(model: nn.Module, loader: DataLoader) -> dict:
    model.eval()
    preds: List[np.ndarray] = []
    targets: List[np.ndarray] = []
    with torch.no_grad():
        for inputs, y in loader:
            inputs = inputs.to(DEVICE)
            y = y.to(DEVICE)
            out = model(inputs)[0] if isinstance(model, FeatureWeightedModel) else model(inputs)[0]
            preds.append(out.cpu().numpy())
            targets.append(y.cpu().numpy())
    y_pred = np.concatenate(preds)
    y_true = np.concatenate(targets)

    # Regression metrics
    mse = float(np.mean((y_pred - y_true) ** 2))
    mae = float(np.mean(np.abs(y_pred - y_true)))
    ss_res = float(np.sum((y_true - y_pred) ** 2))
    ss_tot = float(np.sum((y_true - np.mean(y_true)) ** 2))
    r2 = float("nan") if ss_tot == 0 else float(1.0 - ss_res / ss_tot)

    return {"mse": mse, "mae": mae, "r2": r2}


# --------------------------------------------------------------------------- #
# Comparison-model specific training/eval
# --------------------------------------------------------------------------- #
def train_comparison_model(
    model: nn.Module,
    train_loader: DataLoader,
    val_loader: Optional[DataLoader],
    cfg: TrainConfig,
):
    criterion = nn.BCELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)

    best_state = None
    best_val = float("inf")
    patience = 0

    for epoch in range(1, cfg.epochs + 1):
        model.train()
        train_loss = 0.0
        for left_feat, right_feat, target in train_loader:
            left_feat = left_feat.to(DEVICE)
            right_feat = right_feat.to(DEVICE)
            target = target.to(DEVICE)

            pred, _, _ = model(left_feat, right_feat)
            loss = criterion(pred, target)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * target.size(0)

        if val_loader is not None:
            model.eval()
            val_loss = 0.0
            with torch.no_grad():
                for left_feat, right_feat, target in val_loader:
                    left_feat = left_feat.to(DEVICE)
                    right_feat = right_feat.to(DEVICE)
                    target = target.to(DEVICE)
                    pred, _, _ = model(left_feat, right_feat)
                    val_loss += criterion(pred, target).item() * target.size(0)
            avg_val = val_loss / len(val_loader.dataset)
            if avg_val < best_val - 1e-5:
                best_val = avg_val
                best_state = model.state_dict()
                patience = 0
            else:
                patience += 1
            if patience >= cfg.patience:
                break
        else:
            best_state = model.state_dict()

    if best_state is not None:
        model.load_state_dict(best_state)
    return model


def evaluate_comparison_model(model: nn.Module, loader: DataLoader) -> dict:
    preds: List[np.ndarray] = []
    targets: List[np.ndarray] = []
    with torch.no_grad():
        for left_feat, right_feat, target in loader:
            left_feat = left_feat.to(DEVICE)
            right_feat = right_feat.to(DEVICE)
            target = target.to(DEVICE)
            pred, _, _ = model(left_feat, right_feat)
            preds.append(pred.cpu().numpy())
            targets.append(target.cpu().numpy())
    y_pred = np.concatenate(preds)
    y_true = np.concatenate(targets)
    mse = float(np.mean((y_pred - y_true) ** 2))
    mae = float(np.mean(np.abs(y_pred - y_true)))
    ss_res = float(np.sum((y_true - y_pred) ** 2))
    ss_tot = float(np.sum((y_true - np.mean(y_true)) ** 2))
    r2 = float("nan") if ss_tot == 0 else float(1.0 - ss_res / ss_tot)
    return {"mse": mse, "mae": mae, "r2": r2}


# --------------------------------------------------------------------------- #
# Stage-aware comparison model utilities
# --------------------------------------------------------------------------- #
def train_stage_aware_model(
    model: StageAwareSharedComparisonModel,
    train_loader: DataLoader,
    val_loader: Optional[DataLoader],
    cfg: TrainConfig,
):
    criterion = nn.BCELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)
    best_state = None
    best_val = float("inf")
    patience = 0

    for epoch in range(1, cfg.epochs + 1):
        model.train()
        for left_seq, right_seq, target in train_loader:
            left_seq = left_seq.to(DEVICE)
            right_seq = right_seq.to(DEVICE)
            target = target.to(DEVICE)
            pred, _, _, _, _ = model(left_seq, right_seq)
            loss = criterion(pred, target)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        if val_loader is not None:
            model.eval()
            val_loss = 0.0
            with torch.no_grad():
                for left_seq, right_seq, target in val_loader:
                    left_seq = left_seq.to(DEVICE)
                    right_seq = right_seq.to(DEVICE)
                    target = target.to(DEVICE)
                    pred, _, _, _, _ = model(left_seq, right_seq)
                    val_loss += criterion(pred, target).item() * target.size(0)
            avg_val = val_loss / len(val_loader.dataset)
            if avg_val < best_val - 1e-5:
                best_val = avg_val
                best_state = model.state_dict()
                patience = 0
            else:
                patience += 1
            if patience >= cfg.patience:
                break
        else:
            best_state = model.state_dict()

    if best_state is not None:
        model.load_state_dict(best_state)
    return model


def evaluate_stage_aware_model(model: StageAwareSharedComparisonModel, loader: DataLoader) -> dict:
    model.eval()
    preds: List[np.ndarray] = []
    targets: List[np.ndarray] = []
    with torch.no_grad():
        for left_seq, right_seq, target in loader:
            left_seq = left_seq.to(DEVICE)
            right_seq = right_seq.to(DEVICE)
            target = target.to(DEVICE)
            pred, _, _, _, _ = model(left_seq, right_seq)
            preds.append(pred.cpu().numpy())
            targets.append(target.cpu().numpy())
    y_pred = np.concatenate(preds)
    y_true = np.concatenate(targets)
    mse = float(np.mean((y_pred - y_true) ** 2))
    mae = float(np.mean(np.abs(y_pred - y_true)))
    ss_res = float(np.sum((y_true - y_pred) ** 2))
    ss_tot = float(np.sum((y_true - np.mean(y_true)) ** 2))
    r2 = float("nan") if ss_tot == 0 else float(1.0 - ss_res / ss_tot)
    return {"mse": mse, "mae": mae, "r2": r2}


def aggregate_stage_aware_weights(model, loader: DataLoader):
    if loader is None:
        return None
    model.eval()
    left_stage_sum = right_stage_sum = left_feat_sum = right_feat_sum = None
    left_per_feature_weights = right_per_feature_weights = None
    total = 0
    is_per_feature_model = isinstance(model, StageAwareSharedComparisonUnified)

    with torch.no_grad():
        for left_seq, right_seq, _ in loader:
            left_seq = left_seq.to(DEVICE)
            right_seq = right_seq.to(DEVICE)
            pred, left_stage, right_stage, left_feat_gate, right_feat_gate = model(left_seq, right_seq)
            batch_size = left_seq.size(0)
            total += batch_size

            # Handle different weight shapes
            if left_stage.dim() == 3:  # (batch, n_features, T) - PerFeatureTimeAttention
                # For per-feature visualization, collect all weights
                if left_per_feature_weights is None:
                    left_per_feature_weights = left_stage.sum(dim=0)  # (n_features, T)
                    right_per_feature_weights = right_stage.sum(dim=0)  # (n_features, T)
                else:
                    left_per_feature_weights += left_stage.sum(dim=0)
                    right_per_feature_weights += right_stage.sum(dim=0)

                # Average across features for stage weights: (batch, T)
                ls = left_stage.mean(dim=1).sum(dim=0)
                rs = right_stage.mean(dim=1).sum(dim=0)
            else:  # (batch, T) - regular AdditiveTimeAttention
                ls = left_stage.sum(dim=0)
                rs = right_stage.sum(dim=0)

            lf = left_feat_gate.detach().sum(dim=0)
            rf = right_feat_gate.detach().sum(dim=0)
            left_stage_sum = ls if left_stage_sum is None else left_stage_sum + ls
            right_stage_sum = rs if right_stage_sum is None else right_stage_sum + rs
            left_feat_sum = lf if left_feat_sum is None else left_feat_sum + lf
            right_feat_sum = rf if right_feat_sum is None else right_feat_sum + rf

    if total == 0:
        return None

    left_stage_mean = (left_stage_sum / total).cpu().numpy()
    right_stage_mean = (right_stage_sum / total).cpu().numpy()
    left_feat_mean = (left_feat_sum / total).cpu().numpy()
    right_feat_mean = (right_feat_sum / total).cpu().numpy()

    result = {
        "left_stage": left_stage_mean,
        "right_stage": right_stage_mean,
        "left_feature": left_feat_mean,
        "right_feature": right_feat_mean,
    }

    if is_per_feature_model and left_per_feature_weights is not None:
        # Store per-feature time weights for visualization
        result["left_per_feature_time"] = (left_per_feature_weights / total).cpu().numpy()
        result["right_per_feature_time"] = (right_per_feature_weights / total).cpu().numpy()

    if isinstance(model, StageAwareSharedComparisonUnified):
        result["shared_stage"] = left_stage_mean  # same for both

    return result


def _plot_bar(values: np.ndarray, labels: List[str], title: str, path: str):
    plt.figure(figsize=(max(6, len(labels) * 0.6), 4))
    idx = np.arange(len(values))
    plt.bar(idx, values)
    plt.xticks(idx, labels, rotation=45, ha="right")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(path, dpi=200)
    plt.close()


def visualize_stage_aware_weights(
    weights: dict,
    stage_labels: List[str],
    feature_labels: List[str],
    output_dir: str,
):
    os.makedirs(output_dir, exist_ok=True)
    shared_stage = weights.get("shared_stage")
    left_stage = weights["left_stage"]
    right_stage = weights["right_stage"]
    left_feat = weights["left_feature"]
    right_feat = weights["right_feature"]

    np.savetxt(os.path.join(output_dir, "left_stage_attention.csv"), left_stage, delimiter=",")
    np.savetxt(os.path.join(output_dir, "right_stage_attention.csv"), right_stage, delimiter=",")
    np.savetxt(os.path.join(output_dir, "left_feature_attention.csv"), left_feat, delimiter=",")
    np.savetxt(os.path.join(output_dir, "right_feature_attention.csv"), right_feat, delimiter=",")

    stage_labels = stage_labels or [f"Stage {i+1}" for i in range(len(left_stage))]
    feature_labels = feature_labels or [f"feat_{i+1}" for i in range(len(left_feat))]

    if shared_stage is not None:
        _plot_bar(
            shared_stage,
            stage_labels,
            "Shared Stage Attention",
            os.path.join(output_dir, "shared_stage_attention.png"),
        )
    else:
        _plot_bar(
            left_stage,
            stage_labels,
            "Left Ear Stage Attention",
            os.path.join(output_dir, "left_stage_attention.png"),
        )
        _plot_bar(
            right_stage,
            stage_labels,
            "Right Ear Stage Attention",
            os.path.join(output_dir, "right_stage_attention.png"),
        )
    _plot_bar(
        left_feat,
        feature_labels,
        "Left Ear Feature Weights",
        os.path.join(output_dir, "left_feature_attention.png"),
    )
    _plot_bar(
        right_feat,
        feature_labels,
        "Right Ear Feature Weights",
        os.path.join(output_dir, "right_feature_attention.png"),
    )


def visualize_per_feature_time_weights(weights: dict, output_dir: str):
    """Visualize per-feature time attention weights for StageAwareSharedComparisonUnified."""
    os.makedirs(output_dir, exist_ok=True)

    if "left_per_feature_time" not in weights:
        print("No per-feature time weights found for visualization")
        return

    left_per_feature = weights["left_per_feature_time"]  # (n_features, T)
    right_per_feature = weights["right_per_feature_time"]  # (n_features, T)

    n_features, n_stages = left_per_feature.shape

    # Create feature labels
    feature_labels = [f"Feature {i+1}" for i in range(n_features)]
    stage_labels = [f"Stage {i+1}" for i in range(n_stages)]

    # Save raw data
    np.savetxt(os.path.join(output_dir, "left_per_feature_time_weights.csv"),
               left_per_feature, delimiter=",", header=",".join(stage_labels))
    np.savetxt(os.path.join(output_dir, "right_per_feature_time_weights.csv"),
               right_per_feature, delimiter=",", header=",".join(stage_labels))

    # Create heatmaps for left and right
    fig, axes = plt.subplots(2, 1, figsize=(12, 10))

    # Left ear heatmap
    im1 = axes[0].imshow(left_per_feature, aspect='auto', cmap='viridis')
    axes[0].set_title('Left Ear: Per-Feature Time Attention Weights', fontsize=14, fontweight='bold')
    axes[0].set_xlabel('Time Stage')
    axes[0].set_ylabel('Feature')
    axes[0].set_xticks(range(n_stages))
    axes[0].set_xticklabels(stage_labels, rotation=45, ha='right')
    axes[0].set_yticks(range(n_features))
    axes[0].set_yticklabels(feature_labels)
    plt.colorbar(im1, ax=axes[0], label='Attention Weight')

    # Right ear heatmap
    im2 = axes[1].imshow(right_per_feature, aspect='auto', cmap='viridis')
    axes[1].set_title('Right Ear: Per-Feature Time Attention Weights', fontsize=14, fontweight='bold')
    axes[1].set_xlabel('Time Stage')
    axes[1].set_ylabel('Feature')
    axes[1].set_xticks(range(n_stages))
    axes[1].set_xticklabels(stage_labels, rotation=45, ha='right')
    axes[1].set_yticks(range(n_features))
    axes[1].set_yticklabels(feature_labels)
    plt.colorbar(im2, ax=axes[1], label='Attention Weight')

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "per_feature_time_attention_heatmap.png"), dpi=300, bbox_inches='tight')
    plt.close()

    # Create line plots for each feature
    fig, axes = plt.subplots(n_features, 2, figsize=(15, 3*n_features), squeeze=False)
    fig.suptitle('Per-Feature Time Attention Patterns', fontsize=16, fontweight='bold')

    colors = plt.cm.tab10(np.linspace(0, 1, n_features))

    for feat_idx in range(n_features):
        # Left ear
        axes[feat_idx, 0].plot(range(n_stages), left_per_feature[feat_idx],
                               marker='o', linewidth=2, color=colors[feat_idx])
        axes[feat_idx, 0].set_title(f'Left Ear - {feature_labels[feat_idx]}')
        axes[feat_idx, 0].set_xlabel('Time Stage')
        axes[feat_idx, 0].set_ylabel('Attention Weight')
        axes[feat_idx, 0].grid(True, alpha=0.3)

        # Right ear
        axes[feat_idx, 1].plot(range(n_stages), right_per_feature[feat_idx],
                               marker='o', linewidth=2, color=colors[feat_idx])
        axes[feat_idx, 1].set_title(f'Right Ear - {feature_labels[feat_idx]}')
        axes[feat_idx, 1].set_xlabel('Time Stage')
        axes[feat_idx, 1].set_ylabel('Attention Weight')
        axes[feat_idx, 1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "per_feature_time_attention_lines.png"), dpi=300, bbox_inches='tight')
    plt.close()

    # Create summary statistics
    left_stats = {
        'mean_attention': left_per_feature.mean(axis=1),
        'peak_stage': left_per_feature.argmax(axis=1),
        'attention_variance': left_per_feature.var(axis=1)
    }

    right_stats = {
        'mean_attention': right_per_feature.mean(axis=1),
        'peak_stage': right_per_feature.argmax(axis=1),
        'attention_variance': right_per_feature.var(axis=1)
    }

    # Plot summary statistics
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # Mean attention per feature
    x = np.arange(n_features)
    width = 0.35
    axes[0].bar(x - width/2, left_stats['mean_attention'], width, label='Left Ear', alpha=0.8)
    axes[0].bar(x + width/2, right_stats['mean_attention'], width, label='Right Ear', alpha=0.8)
    axes[0].set_xlabel('Feature')
    axes[0].set_ylabel('Mean Attention Weight')
    axes[0].set_title('Average Attention per Feature')
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(feature_labels, rotation=45, ha='right')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Peak attention stage per feature
    axes[1].scatter(x, left_stats['peak_stage'], label='Left Ear', s=80, alpha=0.8)
    axes[1].scatter(x, right_stats['peak_stage'], label='Right Ear', s=80, marker='s', alpha=0.8)
    axes[1].set_xlabel('Feature')
    axes[1].set_ylabel('Peak Attention Stage')
    axes[1].set_title('Peak Attention Timing per Feature')
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(feature_labels, rotation=45, ha='right')
    axes[1].set_yticks(range(n_stages))
    axes[1].set_yticklabels(stage_labels)
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    # Attention variance per feature
    axes[2].bar(x - width/2, left_stats['attention_variance'], width, label='Left Ear', alpha=0.8)
    axes[2].bar(x + width/2, right_stats['attention_variance'], width, label='Right Ear', alpha=0.8)
    axes[2].set_xlabel('Feature')
    axes[2].set_ylabel('Attention Variance')
    axes[2].set_title('Attention Distribution Spread per Feature')
    axes[2].set_xticks(x)
    axes[2].set_xticklabels(feature_labels, rotation=45, ha='right')
    axes[2].legend()
    axes[2].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, "per_feature_time_attention_summary.png"), dpi=300, bbox_inches='tight')
    plt.close()

    print(f"Per-feature time attention visualizations saved to: {output_dir}")


# --------------------------------------------------------------------------- #
# Main runner
# --------------------------------------------------------------------------- #
def build_datasets(stage_seconds: float):
    project_root = os.getcwd()
    base_dir = r"D:\D\research\audioset下载\clap_select"

    # Load pair list & targets
    diff_raw, diff_z, pair_names = load_or_extract_features(project_root)
    merged = merge_balanced_pairs_by_type(pair_names)
    all_pair_names: List[str] = []
    for key in ["nn_main", "nn_sub", "main", "sub"]:
        if key in merged:
            all_pair_names.extend(merged[key]["pair_names"])
    trials = get_trials()
    probs = calculate_selection_probability_144(all_pair_names, trials).astype(np.float32)

    feature_configs = get_feature_configs_from_linear_regression()
    cached_dataset = load_or_build_cached_dataset(
        feature_configs=feature_configs,
        project_root=project_root,
        base_dir=base_dir,
        sr=SR,
        hop_length=HOP,
        window_size=5,
        use_high_res=False,
    )

    stage_dataset = StageFeatureDataset(
        cached_dataset,
        stage_seconds=stage_seconds,
        feature_configs=feature_configs,
    )
    return stage_dataset


def _make_datasets(stage_dataset: StageFeatureDataset, indices: np.ndarray):
    feature_ds = FeatureOnlyDataset(stage_dataset, indices)
    stage_ds = StageDiffDataset(stage_dataset, indices)
    comparison_ds = LeftRightDataset(stage_dataset, indices)
    sequence_ds = StageSequenceDataset(stage_dataset, indices)
    return feature_ds, stage_ds, comparison_ds, sequence_ds


def _make_loader(dataset: Dataset, batch_size: int, shuffle: bool = False):
    if dataset is None or len(dataset) == 0:
        return None
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)


def run_pipeline():
    project_root = os.getcwd()
    output_root = os.path.join(project_root, "feature_stage_attention_results")
    os.makedirs(output_root, exist_ok=True)
    stage_dataset = build_datasets(stage_seconds=DEFAULT_STAGE_SECONDS)
    n_samples = len(stage_dataset)
    print(f"\n=== 数据集规模检查 ===")
    print(f"StageFeatureDataset 总样本数: {n_samples}")
    rng = np.random.RandomState(RNG_SEED)
    all_indices = rng.permutation(n_samples)
    folds = np.array_split(all_indices, 5)

    cfg = TrainConfig()
    fw_metrics_list = []
    stage_metrics_list = []
    shared_metrics_list = []
    indep_metrics_list = []
    stage_aware_metrics_list = []
    stage_aware_unified_metrics_list = []
    stage_gru_metrics_list = []
    simple_temp_metrics_list = []

    for fold_idx, test_idx in enumerate(folds, start=1):
        fold_dir = os.path.join(output_root, f"fold_{fold_idx}")
        os.makedirs(fold_dir, exist_ok=True)
        train_val_idx = np.setdiff1d(all_indices, test_idx, assume_unique=True)
        rng_fold = np.random.RandomState(RNG_SEED + fold_idx)
        rng_fold.shuffle(train_val_idx)
        train_cut = max(1, int(len(train_val_idx) * 0.9))
        train_idx = train_val_idx[:train_cut]
        val_idx = train_val_idx[train_cut:] if len(train_val_idx) > train_cut else np.array([], dtype=int)

        print(f"\n[Fold {fold_idx}/5 数据划分]")
        print(f"  训练集样本数: {len(train_idx)}")
        print(f"  验证集样本数: {len(val_idx)}")
        print(f"  测试集样本数: {len(test_idx)}")

        feature_train, stage_train, comparison_train, sequence_train = _make_datasets(stage_dataset, train_idx)
        if len(val_idx) > 0:
            feature_val, stage_val, comparison_val, sequence_val = _make_datasets(stage_dataset, val_idx)
        else:
            feature_val = stage_val = comparison_val = sequence_val = None
        feature_test, stage_test, comparison_test, sequence_test = _make_datasets(stage_dataset, test_idx)

        feature_dim = feature_train[0][0].shape[0]
        feature_model = FeatureWeightedModel(feature_dim=feature_dim).to(DEVICE)
        fw_train_loader = _make_loader(feature_train, cfg.batch_size, shuffle=True)
        fw_val_loader = _make_loader(feature_val, cfg.batch_size) if feature_val else None
        fw_test_loader = _make_loader(feature_test, cfg.batch_size)

        feature_model, _, _ = train_model(feature_model, fw_train_loader, fw_val_loader, cfg)
        fold_fw_metrics = evaluate_model(feature_model, fw_test_loader)
        fw_metrics_list.append(fold_fw_metrics)

        stage_shape = stage_train[0][0].shape
        stage_model = FeatureStageAttentionModel(
            n_stages=stage_shape[0],
            feature_dim=stage_shape[1],
        ).to(DEVICE)
        stage_train_loader = _make_loader(stage_train, cfg.batch_size, shuffle=True)
        stage_val_loader = _make_loader(stage_val, cfg.batch_size) if stage_val else None
        stage_test_loader = _make_loader(stage_test, cfg.batch_size)

        stage_model, _, _ = train_model(stage_model, stage_train_loader, stage_val_loader, cfg)
        fold_stage_metrics = evaluate_model(stage_model, stage_test_loader)
        stage_metrics_list.append(fold_stage_metrics)

        # FeatureStageGRUModel - 基于GRU的时间累加
        stage_gru_model = FeatureStageGRUModel(
            n_stages=stage_shape[0],
            feature_dim=stage_shape[1],
        ).to(DEVICE)
        stage_gru_train_loader = _make_loader(stage_train, cfg.batch_size, shuffle=True)
        stage_gru_val_loader = _make_loader(stage_val, cfg.batch_size) if stage_val else None
        stage_gru_test_loader = _make_loader(stage_test, cfg.batch_size)

        print(f"    GRU训练数据: {len(stage_train)} 样本")
        if stage_val:
            print(f"    GRU验证数据: {len(stage_val)} 样本")
        print(f"    GRU测试数据: {len(stage_test)} 样本")

        # 为GRU模型使用更长的训练时间和更小的学习率
        gru_cfg = TrainConfig(lr=5e-4, epochs=100, patience=20)
        print(f"    GRU模型训练开始...")
        stage_gru_model, _, _ = train_model(stage_gru_model, stage_gru_train_loader, stage_gru_val_loader, gru_cfg)
        print(f"    GRU模型训练完成")
        fold_stage_gru_metrics = evaluate_model(stage_gru_model, stage_gru_test_loader)
        stage_gru_metrics_list.append(fold_stage_gru_metrics)

        # SimpleTemporalModel - 极简时间建模
        simple_temp_model = SimpleTemporalModel(
            n_stages=stage_shape[0],
            feature_dim=stage_shape[1],
            hidden_dim=16
        ).to(DEVICE)
        simple_temp_train_loader = _make_loader(stage_train, cfg.batch_size, shuffle=True)
        simple_temp_val_loader = _make_loader(stage_val, cfg.batch_size) if stage_val else None
        simple_temp_test_loader = _make_loader(stage_test, cfg.batch_size)

        simple_temp_model, _, _ = train_model(simple_temp_model, simple_temp_train_loader, simple_temp_val_loader, cfg)
        fold_simple_temp_metrics = evaluate_model(simple_temp_model, simple_temp_test_loader)
        simple_temp_metrics_list.append(fold_simple_temp_metrics)


        ear_feat_dim = comparison_train.stage_dataset.left_feat_dim
        shared_model = SharedEarComparisonModel(ear_feature_dim=ear_feat_dim).to(DEVICE)
        indep_model = IndependentEarComparisonModel(ear_feature_dim=ear_feat_dim).to(DEVICE)
        comp_train_loader = _make_loader(comparison_train, cfg.batch_size, shuffle=True)
        comp_val_loader = _make_loader(comparison_val, cfg.batch_size) if comparison_val else None
        comp_test_loader = _make_loader(comparison_test, cfg.batch_size)

        shared_model = train_comparison_model(shared_model, comp_train_loader, comp_val_loader, cfg)
        fold_shared_metrics = evaluate_comparison_model(shared_model, comp_test_loader)
        shared_metrics_list.append(fold_shared_metrics)

        indep_model = train_comparison_model(indep_model, comp_train_loader, comp_val_loader, cfg)
        fold_indep_metrics = evaluate_comparison_model(indep_model, comp_test_loader)
        indep_metrics_list.append(fold_indep_metrics)

        stage_seq_train_loader = _make_loader(sequence_train, cfg.batch_size, shuffle=True)
        stage_seq_val_loader = _make_loader(sequence_val, cfg.batch_size) if sequence_val else None
        stage_seq_test_loader = _make_loader(sequence_test, cfg.batch_size)

        stage_aware_model = StageAwareSharedComparisonModel(
            ear_feature_dim=stage_dataset.ear_stage_feat_dim,
        ).to(DEVICE)
        stage_aware_model = train_stage_aware_model(stage_aware_model, stage_seq_train_loader, stage_seq_val_loader, cfg)
        fold_stage_aware_metrics = evaluate_stage_aware_model(stage_aware_model, stage_seq_test_loader)
        stage_aware_metrics_list.append(fold_stage_aware_metrics)
        weights = aggregate_stage_aware_weights(stage_aware_model, stage_seq_test_loader)
        if weights is not None:
            visualize_stage_aware_weights(
                weights,
                getattr(stage_dataset, "stage_labels", []),
                getattr(stage_dataset, "ear_feature_labels", []),
                os.path.join(fold_dir, "stage_aware_shared"),
            )

        unified_model = StageAwareSharedComparisonUnified(
            ear_feature_dim=stage_dataset.ear_stage_feat_dim,
        ).to(DEVICE)
        unified_model = train_stage_aware_model(unified_model, stage_seq_train_loader, stage_seq_val_loader, cfg)
        fold_unified_metrics = evaluate_stage_aware_model(unified_model, stage_seq_test_loader)
        stage_aware_unified_metrics_list.append(fold_unified_metrics)
        unified_weights = aggregate_stage_aware_weights(unified_model, stage_seq_test_loader)
        if unified_weights is not None:
            visualize_stage_aware_weights(
                unified_weights,
                getattr(stage_dataset, "stage_labels", []),
                getattr(stage_dataset, "ear_feature_labels", []),
                os.path.join(fold_dir, "stage_aware_shared_time"),
            )
            # Additional per-feature time weight visualization
            if "left_per_feature_time" in unified_weights:
                visualize_per_feature_time_weights(
                    unified_weights,
                    os.path.join(fold_dir, "stage_aware_shared_time", "per_feature_analysis"),
                )

        print(f"\n[Fold {fold_idx}/5]")
        print("  FeatureWeightedModel:", fold_fw_metrics)
        print("  FeatureStageAttentionModel:", fold_stage_metrics)
        print("  SharedEarComparisonModel:", fold_shared_metrics)
        print("  IndependentEarComparisonModel:", fold_indep_metrics)
        print("  StageAwareSharedComparisonModel:", fold_stage_aware_metrics)
        print("  StageAwareSharedComparisonUnified:", fold_unified_metrics)
        print("  FeatureStageGRUModel:", fold_stage_gru_metrics)
        print("  SimpleTemporalModel:", fold_simple_temp_metrics)

    def summarize(metrics_list):
        # 回归指标 (mse, mae, r2)
        mse = np.array([m["mse"] for m in metrics_list])
        mae = np.array([m["mae"] for m in metrics_list])
        r2 = np.array([m["r2"] for m in metrics_list])
        return {
            "mse_mean": float(mse.mean()),
            "mse_std": float(mse.std()),
            "mae_mean": float(mae.mean()),
            "mae_std": float(mae.std()),
            "r2_mean": float(np.nanmean(r2)),  # 处理nan
            "r2_std": float(np.nanstd(r2)),
        }

    print("\n=== 5-fold Summary ===")
    print("FeatureWeightedModel:", summarize(fw_metrics_list))
    print("FeatureStageAttentionModel:", summarize(stage_metrics_list))
    print("SharedEarComparisonModel:", summarize(shared_metrics_list))
    print("IndependentEarComparisonModel:", summarize(indep_metrics_list))
    print("StageAwareSharedComparisonModel:", summarize(stage_aware_metrics_list))
    print("StageAwareSharedComparisonUnified:", summarize(stage_aware_unified_metrics_list))
    print("FeatureStageGRUModel:", summarize(stage_gru_metrics_list))
    print("SimpleTemporalModel:", summarize(simple_temp_metrics_list))


def test_gru_model():
    """测试GRU模型是否正常工作"""
    print("=== 测试FeatureStageGRUModel ===")

    # 创建模型
    model = FeatureStageGRUModel(n_stages=5, feature_dim=10, hidden_dim=32)
    model.eval()

    # 创建测试数据 (回归任务)
    batch_size = 4
    x = torch.randn(batch_size, 5, 10)  # (batch, n_stages, feature_dim)
    y = torch.rand(batch_size)  # 连续标签 (0-1)

    print(f"输入形状: {x.shape}")
    print(f"标签范围: {y.min().item():.4f} - {y.max().item():.4f}")

    # 前向传播
    with torch.no_grad():
        pred, weights = model(x)

    print(f"预测范围: {pred.min().item():.4f} - {pred.max().item():.4f}")
    print(f"预测均值: {pred.mean().item():.4f}")
    print(f"预测标准差: {pred.std().item():.4f}")
    print(f"权重形状: {weights.shape}")

    # 计算MSE
    mse = ((pred - y) ** 2).mean().item()
    print(f"MSE: {mse:.4f}")

    return mse < 1.0  # 如果MSE小于1，说明模型基本正常


if __name__ == "__main__":
    run_pipeline()

